services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:Kyokaicentro2610@localhost:5432/centrodb
    ports:
      - "8000:8000"
    networks:
      - app_net

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/staticfiles:/static
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
    driver: bridge