# Generated by Django 5.2.4 on 2025-07-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoption',
            name='identifier',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
