# Generated by Django 5.2.4 on 2025-07-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classoption_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cycle',
            field=models.CharField(choices=[('M', 'Mensual'), ('S', 'Semestral')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_due',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
