# Generated by Django 5.2.4 on 2025-07-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_cycle_alter_payment_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='credit_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
