# Generated by Django 5.2.4 on 2025-07-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='cuil',
            field=models.CharField(default=11111111111, max_length=11),
            preserve_default=False,
        ),
    ]
